# Generated by Django 4.2.8 on 2024-01-16 15:45

from django.db import migrations, models
import klm.users.models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ("-created_at",)},
        ),
        migrations.AddField(
            model_name="user",
            name="login_otp",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="login_otp_used",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="otp_base32",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="otp_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="otpauth_url",
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="qr_code",
            field=models.ImageField(blank=True, null=True, upload_to=klm.users.models.get_qr_code_file_path),
        ),
    ]
